schema_version = "2.0.0"

id = "i3d_material_visualizer"
version = "1.0.0"
name = "I3D Material Visualizer"
tagline = "Tool for visualizing Farming Simulator materials"
maintainer = "LKAMinco"
type = "add-on"
website = "https://github.com/LKAMinco/FS25-Material-Visualizer"
tags = ["Material"]
blender_version_min = "4.5.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Reading files from Farm Sim game directory"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  ".gitignore",
]